//! Build-time generator: reads the vendored models.dev `models.json` snapshot
//! and emits `model_catalog.zig` — a static table mapping model id to its
//! token limits (context window + max output) for the providers Nova
//! integrates with. Wired into `build.zig`; the emitted file is imported there
//! as the `model_catalog` module and consumed by `compaction.zig`.
//!
//! Invocation (set up by build.zig):
//!   gen-model-catalog <input models.json> <output model_catalog.zig>
//!
//! Only models whose models.dev originator namespace is in `allowed_providers`
//! are emitted, keeping the runtime table lean. Widening Nova's coverage is a
//! one-line edit to that list.

const std = @import("std");

/// models.dev originator namespaces Nova actually routes to. The hardcoded
/// table this replaces only ever covered OpenAI + Anthropic families, so this
/// is a strict, accurate superset of prior coverage. Add a namespace here to
/// widen it.
const allowed_providers = [_][]const u8{ "openai", "anthropic" };

const Entry = struct {
    id: []const u8,
    context: u32,
    output: u32,
};

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const io = init.io;

    var arg_it = try std.process.Args.Iterator.initAllocator(init.minimal.args, gpa);
    defer arg_it.deinit();
    _ = arg_it.next(); // executable path
    const input_path = arg_it.next() orelse return error.MissingInputArg;
    const output_path = arg_it.next() orelse return error.MissingOutputArg;

    const json_bytes = try std.Io.Dir.cwd().readFileAlloc(io, input_path, gpa, .unlimited);
    defer gpa.free(json_bytes);

    const parsed = try std.json.parseFromSlice(std.json.Value, gpa, json_bytes, .{});
    defer parsed.deinit();
    if (parsed.value != .object) return error.RootNotObject;

    var entries: std.ArrayList(Entry) = .empty;
    defer entries.deinit(gpa);

    var it = parsed.value.object.iterator();
    while (it.next()) |kv| {
        // Keys are "<provider>/<model-id>"; Nova prompts with the bare model
        // id, so the originator prefix is only used to filter here.
        const key = kv.key_ptr.*;
        const slash = std.mem.indexOfScalar(u8, key, '/') orelse continue;
        if (!isAllowed(key[0..slash])) continue;
        const model_id = key[slash + 1 ..];
        if (model_id.len == 0) continue;
        if (kv.value_ptr.* != .object) continue;
        const limit = kv.value_ptr.object.get("limit") orelse continue;
        if (limit != .object) continue;
        const context = limitField(limit, "context") orelse continue;
        const output = limitField(limit, "output") orelse 0;
        try entries.append(gpa, .{ .id = model_id, .context = context, .output = output });
    }

    // Sort by id so the generated file is stable across runs (clean diffs).
    std.mem.sort(Entry, entries.items, {}, lessThanById);

    var out: std.Io.Writer.Allocating = .init(gpa);
    defer out.deinit();
    const w = &out.writer;
    try w.writeAll(
        \\// GENERATED by tools/gen_model_catalog.zig from vendor/models.dev/models.json.
        \\// Do not edit by hand — re-run `zig build` to regenerate after refreshing
        \\// the vendored snapshot (curl https://models.dev/models.json).
        \\
        \\/// One model's token limits, keyed by its bare id (no provider prefix).
        \\pub const Entry = struct {
        \\    id: []const u8,
        \\    /// Context window in tokens.
        \\    context: u32,
        \\    /// Maximum output tokens (0 when models.dev omits it).
        \\    output: u32,
        \\};
        \\
        \\/// Sorted by `id` so callers may assume deterministic order.
        \\pub const entries = [_]Entry{
        \\
    );
    for (entries.items) |entry| {
        try w.print(
            "    .{{ .id = \"{s}\", .context = {d}, .output = {d} }},\n",
            .{ entry.id, entry.context, entry.output },
        );
    }
    try w.writeAll("};\n");

    const file = try std.Io.Dir.cwd().createFile(io, output_path, .{});
    defer file.close(io);
    try file.writeStreamingAll(io, out.written());
}

fn isAllowed(provider: []const u8) bool {
    for (allowed_providers) |allowed| {
        if (std.mem.eql(u8, allowed, provider)) return true;
    }
    return false;
}

/// Read an integer field out of a models.dev `limit` object, clamped into the
/// `u32` domain. Null when the field is absent or not an integer.
fn limitField(limit: std.json.Value, name: []const u8) ?u32 {
    const value = limit.object.get(name) orelse return null;
    if (value != .integer) return null;
    if (value.integer < 0) return 0;
    if (value.integer > std.math.maxInt(u32)) return std.math.maxInt(u32);
    return @intCast(value.integer);
}

fn lessThanById(_: void, a: Entry, b: Entry) bool {
    return std.mem.lessThan(u8, a.id, b.id);
}
