//! Build-time generator: reads the vendored models.dev `models.json` and
//! `api.json` snapshots and emits one module:
//!
//!   `model_catalog.zig` — static table mapping model id → token limits
//!
//! Invocation (set up by build.zig):
//!   gen-model-catalog <models.json> <api.json> <model_catalog.zig>
//!
//! Refresh by re-curling both files and rebuilding:
//!   curl -o vendor/models.dev/models.json https://models.dev/models.json
//!   curl -o vendor/models.dev/api.json    https://models.dev/api.json
//!   zig build

const std = @import("std");

const ModelEntry = struct {
    id: []const u8,
    context: u32,
    output: u32,
};

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const io = init.io;

    var arg_it = try std.process.Args.Iterator.initAllocator(init.minimal.args, gpa);
    defer arg_it.deinit();
    _ = arg_it.next(); // executable path
    const models_path = arg_it.next() orelse return error.MissingModelsArg;
    _ = arg_it.next() orelse return error.MissingApiArg; // api.json kept for build.zig arg compat
    const model_catalog_path = arg_it.next() orelse return error.MissingModelCatalogArg;

    // ── Read models.json (model → token limits) ──
    const models_bytes = try std.Io.Dir.cwd().readFileAlloc(io, models_path, gpa, .unlimited);
    defer gpa.free(models_bytes);

    const models_parsed = try std.json.parseFromSlice(std.json.Value, gpa, models_bytes, .{});
    defer models_parsed.deinit();
    if (models_parsed.value != .object) return error.ModelsRootNotObject;

    var model_entries: std.ArrayList(ModelEntry) = .empty;
    defer model_entries.deinit(gpa);

    {
        var it = models_parsed.value.object.iterator();
        while (it.next()) |kv| {
            const key = kv.key_ptr.*;
            const slash = std.mem.indexOfScalar(u8, key, '/') orelse continue;
            const model_id = key[slash + 1 ..];
            if (model_id.len == 0) continue;
            if (kv.value_ptr.* != .object) continue;
            const limit = kv.value_ptr.object.get("limit") orelse continue;
            if (limit != .object) continue;
            const context = limitField(limit, "context") orelse continue;
            const output = limitField(limit, "output") orelse 0;
            try model_entries.append(gpa, .{ .id = model_id, .context = context, .output = output });
        }
    }
    std.mem.sort(ModelEntry, model_entries.items, {}, lessThanById(ModelEntry));

    // ── Write model_catalog.zig ──
    {
        if (std.fs.path.dirname(model_catalog_path)) |dir| {
            try std.Io.Dir.createDirPath(.cwd(), io, dir);
        }

        var out: std.Io.Writer.Allocating = .init(gpa);
        defer out.deinit();
        const w = &out.writer;

        try w.writeAll(
            \\// GENERATED by tools/gen_model_catalog.zig from vendor/models.dev/models.json.
            \\// Do not edit by hand.
            \\
            \\pub const Entry = struct {
            \\    id: []const u8,
            \\    context: u32,
            \\    output: u32,
            \\};
            \\
            \\pub const entries = [_]Entry{
            \\
        );
        for (model_entries.items) |entry| {
            try w.print("    .{{ .id = \"{s}\", .context = {d}, .output = {d} }},\n", .{ entry.id, entry.context, entry.output });
        }
        try w.writeAll("};\n");

        const file = try std.Io.Dir.cwd().createFile(io, model_catalog_path, .{});
        defer file.close(io);
        try file.writeStreamingAll(io, out.written());
    }
}

fn limitField(limit: std.json.Value, name: []const u8) ?u32 {
    const value = limit.object.get(name) orelse return null;
    if (value != .integer) return null;
    if (value.integer < 0) return 0;
    if (value.integer > std.math.maxInt(u32)) return std.math.maxInt(u32);
    return @intCast(value.integer);
}

fn lessThanById(comptime T: type) fn (void, T, T) bool {
    return struct {
        fn cmp(_: void, a: T, b: T) bool {
            return std.mem.lessThan(u8, a.id, b.id);
        }
    }.cmp;
}
